version: '3.4'

services:

  postgres:
    image: 'postgres:alpine'
    container_name: postgres_easyb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password